name: DeployF1

on:
    push:
        branches:
        - main

permissions:
    contents: write
    pull-requests: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:

            - name: deploy pagina
              uses: actions/checkout@v2

            - name: Desplego la pagina
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./frontend
                publish_branch: gh-pages